# Generated by Django 5.2.6 on 2025-09-03 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "text",
                    models.TextField(help_text="The lesson content to be processed"),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("history", "History"),
                            ("biology", "Biology"),
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                            ("mathematics", "Mathematics"),
                            ("literature", "Literature"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("kids", "Kids"),
                            ("teens", "Teens"),
                            ("college", "College"),
                            ("professional", "Professional"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "prompt",
                    models.TextField(
                        help_text="The refined prompt sent to the 3D generation API"
                    ),
                ),
                (
                    "model_url",
                    models.URLField(
                        blank=True, help_text="URL to the generated 3D model", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued for Processing"),
                            ("extracting", "Extracting Scene"),
                            ("refining", "Refining Prompt"),
                            ("generating", "Generating 3D Model"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="nexus.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApiUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_name",
                    models.CharField(
                        choices=[
                            ("gemini", "Google Gemini API"),
                            ("modelslab", "ModelsLab API"),
                        ],
                        max_length=50,
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("tokens_used", models.IntegerField(default=0)),
                ("successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_calls",
                        to="nexus.lesson",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_calls",
                        to="nexus.scene",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["api_name", "created_at"],
                        name="nexus_apius_api_nam_740174_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="nexus_apius_user_id_96df5e_idx",
                    ),
                ],
            },
        ),
    ]
