# Generated by Django 5.2.6 on 2025-09-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nexus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="storage_key",
            field=models.CharField(
                blank=True,
                help_text="Storage key for the 3D model file",
                max_length=255,
                null=True,
            ),
        ),
    ]
